In [140]:
import numpy as np
import pandas
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.datasets import load_boston
from sklearn.neighbors import KNeighborsRegressor
data = pandas.read_csv("titanic.csv", index_col= "PassengerId")

#задание 2 недели
##
wino_data=pandas.read_csv("wine.data");
classes=wino_data.iloc[:,0]
priznaki=wino_data.iloc[:,1:16]
kf = KFold(n_splits=5, shuffle=True, random_state=42)
#print(cross_val_score(classes,P_scaled,cv=kf))
count_neighbour=np.arange(1,51)
pustoy_massiv=[]
for i in count_neighbour:
 knn = KNeighborsClassifier(n_neighbors=i)
 cross_val = cross_val_score(knn, priznaki, classes, cv=kf , scoring='accuracy')
 pustoy_massiv.append(cross_val.mean())
print(max(pustoy_massiv))
##
P_scaled = preprocessing.scale(priznaki)
massiv=[]
for i in count_neighbour:
    knn=KNeighborsClassifier(n_neighbors=i)
    cross_val=cross_val_score(knn, P_scaled,classes,cv=kf, scoring='accuracy')
    massiv.append(cross_val.mean())
print("Hello")
print(max(massiv))
print(massiv.index(max(massiv))) 


#2 неделя выбор метрики
dataset=load_boston()
D_scaled = preprocessing.scale(dataset.data)
h=np.linspace (1.0 ,  10.0 ,  num = 200 )
i=1
massiv1=[]
for i in h :
    neigh = KNeighborsRegressor(p=i, metric='minkowski',n_neighbors=5,weights='distance')
    cross_val=cross_val_score(neigh, D_scaled,dataset.target,cv=kf,scoring='neg_mean_squared_error')
    massiv1.append(cross_val.mean())
print("Значение 2 задания")
print(max(massiv1))
print(massiv1.index(max(massiv1)))
#конец 2 недели
sr=np.mean(data['Age'])
med=np.nanmedian(data['Age'])
corr= data['SibSp'].corr(data['Parch'])
data1=data[['Pclass','Fare','Age','Sex']]
d = {'male': True, 'female': False}
data1['Sex']=data1['Sex'].map(d)
data1=data1.fillna(data1.mean())
data2=data['Survived'] 
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(data1, data2)
importances = clf.feature_importances_
print(sr)
print(med)
print(corr)
print(importances)
data['Name'] = data['Name'].str.findall(r'^\w+')
name_passengers=data['Name']


0.7352380952380952


C:\pyp2\lib\site-packages\ipykernel_launcher.py:26: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.


Hello
0.9773015873015873
27
Значение 2 задания
-16.030646734221644
0
29.69911764705882
28.0
0.4148376986201567
[0.11920293 0.31502304 0.2545982  0.31117584]


C:\pyp2\lib\site-packages\ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [75]:
import numpy as np
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
m = np.sum(Z, axis=1)
m=np.nonzero(m>10)
print(m)


(array([1, 4, 5], dtype=int64),)


In [13]:
import numpy as np
Z1=np.eye(3)
Z2=np.eye(3)
print(Z1)
U=np.vstack((Z1, Z2))
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
